# Generated by Django 5.1.7 on 2025-03-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='xp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='littledude',
            name='appearance',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
