# Generated by Django 5.1.7 on 2025-03-29 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0002_littledude_xp_alter_littledude_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='personality',
            field=models.CharField(choices=[('Hater', 'Hater'), ('Shy', 'Shy'), ('Bubbly', 'Bubbly'), ('Stoic', 'Stoic'), ('Wise', 'Wise'), ('Barbarian', 'Barbarian')], default='Bubbly', max_length=40),
        ),
    ]
