# Generated by Django 5.1.7 on 2025-03-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0003_littledude_personality'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='hunger',
            field=models.CharField(choices=[('None', 'None'), ('Peckish', 'Peckish'), ('Starving', 'Starving')], default='None', max_length=40),
        ),
    ]
