# Generated by Django 5.1.7 on 2025-03-29 23:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0004_littledude_hunger'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 19, 50, 36, 207816)),
        ),
    ]
