# Generated by Django 5.1.7 on 2025-03-30 01:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0005_littledude_lastvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='xpToNextLevel',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='littledude',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 21, 50, 12, 862627)),
        ),
    ]
