# Generated by Django 5.1.7 on 2025-03-30 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0006_littledude_xptonextlevel_alter_littledude_lastvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littledude',
            name='hunger',
            field=models.CharField(choices=[('None', 'None'), ('Peckish', 'Peckish'), ('Starving', 'Starving'), ('Dead', 'Dead')], default='None', max_length=40),
        ),
        migrations.AlterField(
            model_name='littledude',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 22, 20, 11, 541001)),
        ),
    ]
