# Generated by Django 5.1.7 on 2025-03-30 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0007_alter_littledude_hunger_alter_littledude_lastvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='onWalk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='littledude',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 22, 46, 35, 807240)),
        ),
    ]
