# Generated by Django 5.1.7 on 2025-03-30 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0008_alter_littledude_lastvisit'),
        ('Dude', '0008_littledude_onwalk_alter_littledude_lastvisit'),
    ]

    operations = [
    ]
