# Generated by Django 5.1.7 on 2025-03-30 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0009_merge_20250330_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='littledude',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 12, 33, 24, 723852)),
        ),
    ]
