# Generated by Django 5.1.7 on 2025-04-01 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0009_merge_20250330_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='lastFeeding',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 10, 53, 38, 981963)),
        ),
        migrations.AlterField(
            model_name='littledude',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 10, 53, 38, 981963)),
        ),
    ]
