# Generated by Django 5.1.7 on 2025-04-01 20:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0010_littledude_lastfeeding_alter_littledude_lastvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='littledude',
            name='chatHistory',
            field=models.TextField(default='Chat History: \n'),
        ),
        migrations.AlterField(
            model_name='littledude',
            name='lastFeeding',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 16, 23, 21, 768217)),
        ),
        migrations.AlterField(
            model_name='littledude',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 1, 16, 23, 21, 768217)),
        ),
    ]
