# Generated by Django 5.1.7 on 2025-04-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dude', '0010_alter_littledude_lastvisit'),
        ('Dude', '0011_littledude_chathistory_alter_littledude_lastfeeding_and_more'),
    ]

    operations = [
    ]
